[project]
name = "spacebar_bridge"
version = "0.1.0"
description = "Discord-Spacebar bridge bot"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "apsw>=3.50.4.0",
    "urllib3>=2.5.0",
    "websocket-client>=1.8.0",
]
